### ISSUE TITLE
Support for Custom Java Location

### ISSUE THREAD

**Issue by JustSimplyKyle** [RPMTW/launcher#78]
**Describe the bug**
When choosing a custom java location, it doesn't work.

**To Reproduce**
1. Go to Settings
2. Set a java path
3. It doesn't launch with the java installed

**Expected behavior**
It should launch minecrarft with my custom java location

**Screenshots**
If applicable, add screenshots to help explain your problem.1

**RPMLauncher log (The file is located at `RPMLauncher data storage location/logs/bug time.txt`.)**
```
Please post the information from the log file here
```

**Info (please complete the following information):**
 - OS: Linux
 - RPMLauncher Version 1.0.0.596+4+gc10d9a7-1

**Additional context**

**Comment by SiongSng** [comment]
Please post log
